### PR TITLE
convert multibandsplit and eq3 to typescript

### PR DESCRIPTION
**Pull request by garrensmith**
This converts multibandsplit and the EQ3 to typescript. Hopefully this time you won't need to do so many fixes. I'm a little unsure of the `low`, `mid` and `high` parameters on the EQ3. Not sure if they should be a Param or Signal.

### CODE REVIEW

**Comment by garrensmith** [comment]
I've pushed a few more commits around linting. Let me know if you would prefer that in a separate PR.

**Comment by tambien** [comment]
thanks for the PR very much appreciated! Could you submit the linting changes in a separate PR?

Also no worries about me needing to clean things up, it still saves me a bunch of time to start from your contribution!

**Comment by garrensmith** [comment]
@tambien sure, I've removed the linting from this PR and created #505 . Let me know if you need me to fix anything else.

**Comment by tambien** [comment]
looks great thanks!

**Comment by garrensmith** [comment]
One thing I've noticed is the way you merging in my PR's seems to remove me as the author of those commits:

Screenshot 2019-06-26 12 06 22

Which does suck a little, its kind of nice to be attributed in the commit history. If you making lots of changes on the PR's. You can add a co-author to the commit so we are both listed as authors in the commit: https://help.github.com/en/articles/creating-a-commit-with-multiple-authors

**Comment by tambien** [comment]
oh no! i would never want to remove you or any contributor from the commit history! those commits in your screenshot are just merges though, created from incorporating your changes into the codebase which included some changes already. your PRs are just a little earlier in [the history](https://github.com/Tonejs/Tone.js/compare/typescript)

image

and your name will also appear on the files you contributed to

image

i want to fully credit contributors as much as possible. i've always just used the default mechanisms github provides for merging and attributing contributors. i looked quickly to see if other OSS authors add a "co-author" to merges, i couldn't find an example of it looking quickly [here](https://github.com/mrdoob/three.js/commit/31c077fdf4917ad1e675ea2a9122e6bbf01077ac) and [here](https://github.com/webpack/webpack/commit/cea134828369fcc074ed125b5e3bd38cb1366764).

Do other repos use the co-author feature for merging PRs? i'm happy to start if that's the best way to highlight the work of contributors

**Comment by garrensmith** [comment]
Oh man, I'm so sorry. I didn't look far enough down. Really sorry. Keep doing what you doing. You can look to have less commits if you want. It depends on how strict you are about git history. An example is on the pouchdb repo https://github.com/pouchdb/pouchdb/commits/master Where each commit is linked to a PR or issue so we can track all history. But if you happy how it is then keep going.

Again really sorry for complaining unnecessarily.  I'm on vacation for the next few weeks. I'll look to help more with the typescript once I'm back.

**Comment by tambien** [comment]
that's no problem at all! glad we cleared it up! 

i will take a look at pouchdb for reference/inspiration on how i can keep a better git history with clearer attribution. thanks for the reference!

**Pull request merged**
