### PR TITLE
no insignificant zeroes in barsBeatsSixteenths

### LINKED ISSUE #246: Time#toBarsBeatsSixteenths() Float Issue
In certain conditions, I believe the `Time#toBarsBeatsSixteenths()` function can output undesired results due to floating point math.

The specific conditions I can recreate with:
1. BPM of 100
2. a Time object occurring at `0:1:3`
3. the output of that Time object's `toBarsBeatsSixteenths()` will yield `0:1:3.000`

[Reproduced in JS Bin](https://jsbin.com/kaseyasedu/2/edit?html,js,console)

### PR DESCRIPTION
**Pull request by JackCA**
- fixes #246

### CODE REVIEW

**Comment by JackCA** [comment]
I believe the failures in the CI run are unrelated?

**Comment by tambien** [comment]
i think the test failures might be because you change the bpm in your test, but never change it back to 120. 

i'll add a `beforeEach` method which sets the Transport's bpm to 120 to safeguard against this in the future

**Comment by JackCA** [comment]
@tambien, oh shoot. Yeah that sounds like it's the issue. Let me know if you want me to reset it back to its original value exclusively for this test in lieu of the global beforeEach.

**Comment by tambien** [comment]
@JackCA yes please could you make that change quickly and then the tests will pass and i will merge. I'll look into the beforeEach thing to simplify writing tests for future contributors

**Comment by JackCA** [comment]
@tambien done

**Comment by JackCA** [comment]
@tambien I'm attempting to open another pull-request to fix an issue related to this, but the dev branch you recently merged into master doesn't appear to have any of the changes from this PR. 

Should I be using a different branch, or were these changes lost somewhere?

**Pull request merged**
