### PR TITLE
P5 tone

### PR DESCRIPTION
**Pull request by polyrhythmatic**
Removes all the messed up commits.

Updates p5

### CODE REVIEW

**Comment by polyrhythmatic** [comment]
I don't know why it wants to merge all your commits with mine... this branch was not rebased

**Comment by tambien** [comment]
what's the difference between this one and #88? This one seems to have more commits from me and conflicts (probably because of those commits). We should probably close this one and stick with the other one no?

**Comment by polyrhythmatic** [comment]
yea - I'm not sure what's going on. Is this actually showing as me adding your commits? or is it simply showing the history? I don't know how to commit this without your commits showing up as well. I didn't rebase this branch or anything, it should be just the changes and then a conflict with the readme.

**Comment by tambien** [comment]
Yes. those commits are part of the PR. You also include the README which is where those changes came from. 

did you rebase from master or from dev?

**Comment by polyrhythmatic** [comment]
There was no rebase on this PR, which is why I am so completely confused by this. 

README shows as changed because without rebasing, the changes you made to README from when this branch was created, up to the current dev branch always throws a merge error. I've made no changes to the README and it still throws a merge error.

#88 was rebased from dev

I will try pulling from upstream/dev and incorporating my changes into that branch, then making a pull request. I think this is the only way to solve it. I would love to understand what is going on here - I thought rebasing would bring my branch up to date with the current dev.

**Pull request closed without merging**
