### PR TITLE
Refactored Scale.js to work at audio rate.

### PR DESCRIPTION
**Pull request by Foaly**
Hi there!
I reworked `Scale.js` to work at audio rate using only Signal objects. I was sticking to the tests while refactoring, which are all passing now. I hope there were no side effects I missed.
I don't have a lot of experience developing JavaScript libraries and this is my first time playing with web audio, so I can't really judge, if this change is a performance improvement or how it affects other object depending on `Scale`.
Any feedback is very welcome :)

### CODE REVIEW

**Comment by Foaly** [comment]
This was meant to fix #513. While all tests are passing now and there are no more console errors, I still can't modulate the `PitchShift` `pitch` property. Is there anything else down the line (in `LFO` or `PitchShift`) that I have to change to make this change affect the `pitch` property? I couldn't see anything obvious.

Here is the code I used for testing:
```javascript
  shifter = new Tone.PitchShift(0).toMaster();

  pitchShiftSignal = new Tone.Signal(0, Tone.Type.Interval);
  pitchShiftSignal.connect(shifter.pitch);

  player = new Tone.Player("sound.wav").connect(shifter);
  player.loop = true;

  $("#playButton").click(function() {
    player.start();

    pitchShiftSignal.linearRampTo(2, 2);
  });
```

**Comment by tambien** [comment]
nicely done! but i'm really sorry, i may have led you astray. Scale min/max being signal-rate is one of the reasons that PitchShift.pitch isn't a Signal parameter, but [looking at the code](https://github.com/Tonejs/Tone.js/blob/dev/Tone/effect/PitchShift.js#L161) again now, there's a few other factors as well. The logic of setting the lfo min/max would also need to be there in order to make pitch a signal-rate property. All of that logic would also need to be implemented as signal-rate parameters. 

Again, this logic might also be best implemented in an AudioWorklet...

**Comment by Foaly** [comment]
Yes... I realized that pretty quickly after implementing this and taking another look at `PitchShift` with my gained understanding on the WebAudio API. From looking at it seems that the algorithm is not really set up to be implemented with just Signals (like the lfo min/max switching). 
But I wasn't really happy with the modulation effect the PitchShift introduced as a side effect at higher pitch values anyway, so I am thinking of maybe implementing a Frequency Shifter using a SSB modulator.

Anyways if this PR is still useful to you and does not impact performance, feel free to merge.

**Comment by tambien** [comment]
Going to close this for now. Thanks for the PR! sorry again for leading you down the wrong route. Don't think it's worth the performance hit of the added components without any use for it currently. will reopen if it turns out to be helpful.

**Pull request closed without merging**
