### PR TITLE
fixes #461

### LINKED ISSUE #461: Disconnect from PanVol Not Working
Unable to disconnect from PanVol

Tone.js v13.8.1

example:
https://jsfiddle.net/timboie/bhemrv2d

### PR DESCRIPTION
**Pull request by tboie**
file change history:

https://github.com/Tonejs/Tone.js/commit/eb8bdc0f3741e155e683504f1eece5d2e90e37b2#diff-54c4c358f8061be4571a2e1a0ac2deefL361

### CODE REVIEW

**Comment by tboie** [comment]
This fix ok?  Does it just need to be re-checked?

**Comment by tambien** [comment]
it did not pass the tests which makes me think that it might not be the solution and the type of failure makes me think that `while` loops infinitely.  i have not had a chance to investigate further.

**Comment by tboie** [comment]
Ok , looking into this

**Comment by tboie** [comment]
The catch block is causing the timeout when a disconnect error is thrown.  Moving it outside the while block.

**Comment by tboie** [comment]
Closing. different pull request has been submitted

**Pull request closed without merging**
